name: app_loja
description: Uma loja para venda de produtos.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  http:
  provider:
  equatable:
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 
  test: 
  mocktail: 0.3.0
  faker: 2.1.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_icons:
  ios: true
  android: true
  image_path_ios: lib/ui/assets/icon/ios.png
  image_path_android: lib/ui/assets/icon/android.png
  adaptive_icon_foreground: lib/ui/assets/icon/foreground.png
  adaptive_icon_background: lib/ui/assets/icon/background.png
